{
  "formatVersion": "1.1",
  "component": {
    "group": "com.quarkdown",
    "module": "quarkdown-install-layout-navigator",
    "version": "2.3.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        }
      ],
      "files": [
        {
          "name": "quarkdown-install-layout-navigator-2.3.1.jar",
          "url": "quarkdown-install-layout-navigator-2.3.1.jar",
          "size": 31097,
          "sha512": "66d8ba4760c9d2d611945e00891bae991758fe3fb79e4f013ee18b8cc16839f2959895ac4366ab99b547d1bf2854c4af808f37b617eb86abaab0cd575fef6376",
          "sha256": "2a67cf27311d547a7e377a2aff81fefee4af2812ad6414c1c1b3643eed3acbb7",
          "sha1": "78765e0ac3fef70984c0b0fda145c427528b253c",
          "md5": "efadd51b9098b0c5e63d6b045cb54897"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.quarkdown",
          "module": "quarkdown-core",
          "version": {
            "requires": "2.3.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        }
      ],
      "files": [
        {
          "name": "quarkdown-install-layout-navigator-2.3.1.jar",
          "url": "quarkdown-install-layout-navigator-2.3.1.jar",
          "size": 31097,
          "sha512": "66d8ba4760c9d2d611945e00891bae991758fe3fb79e4f013ee18b8cc16839f2959895ac4366ab99b547d1bf2854c4af808f37b617eb86abaab0cd575fef6376",
          "sha256": "2a67cf27311d547a7e377a2aff81fefee4af2812ad6414c1c1b3643eed3acbb7",
          "sha1": "78765e0ac3fef70984c0b0fda145c427528b253c",
          "md5": "efadd51b9098b0c5e63d6b045cb54897"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "quarkdown-install-layout-navigator-2.3.1-sources.jar",
          "url": "quarkdown-install-layout-navigator-2.3.1-sources.jar",
          "size": 16504,
          "sha512": "d538c6d4c5cd9aba514b57e1b1cfabab2ac5ed3f7d2a092331504c7cf06161c29aad09a94550bdda2eb0458de3dfd99408f3fc56b8f17b76ae85367ec9ad35eb",
          "sha256": "7b6366b067e3eb02ee6fb1ab733e199bb35aa99401fcfd59ed490a637e0914fc",
          "sha1": "1533b6236966f750a91b066042d94c283df6c3da",
          "md5": "17b39b5da4c01dd53c1845bf12ea65ca"
        },
        {
          "name": "quarkdown-install-layout-navigator-2.3.1-sources.jar",
          "url": "quarkdown-install-layout-navigator-2.3.1-sources.jar",
          "size": 16504,
          "sha512": "d538c6d4c5cd9aba514b57e1b1cfabab2ac5ed3f7d2a092331504c7cf06161c29aad09a94550bdda2eb0458de3dfd99408f3fc56b8f17b76ae85367ec9ad35eb",
          "sha256": "7b6366b067e3eb02ee6fb1ab733e199bb35aa99401fcfd59ed490a637e0914fc",
          "sha1": "1533b6236966f750a91b066042d94c283df6c3da",
          "md5": "17b39b5da4c01dd53c1845bf12ea65ca"
        }
      ]
    }
  ]
}
