{
  "formatVersion": "1.1",
  "component": {
    "group": "com.quarkdown",
    "module": "quarkdown-stdlib",
    "version": "2.3.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        }
      ],
      "files": [
        {
          "name": "quarkdown-stdlib-2.3.1.jar",
          "url": "quarkdown-stdlib-2.3.1.jar",
          "size": 317209,
          "sha512": "cdedcff91c42ca6e910b7216e6720d19633b37c3150438e5757bf253c1ab165fdb224a4a2e2946261ef75dd42d437a6422960608d2c8a3d91bbcea569640cc09",
          "sha256": "76198dcb99f3e273e241f64167c666e1cc7b22526162499b866e4c9b3cb6feb8",
          "sha1": "b398b3df91be5054de8073221527bee9d9107650",
          "md5": "007f3f3070faf26fd3f4bf23d377a63b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.quarkdown",
          "module": "quarkdown-core",
          "version": {
            "requires": "2.3.1"
          }
        },
        {
          "group": "se.sawano.java",
          "module": "alphanumeric-comparator",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "com.github.doyaaaaaken",
          "module": "kotlin-csv-jvm",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.kodein.emoji",
          "module": "emoji-kt",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        }
      ],
      "files": [
        {
          "name": "quarkdown-stdlib-2.3.1.jar",
          "url": "quarkdown-stdlib-2.3.1.jar",
          "size": 317209,
          "sha512": "cdedcff91c42ca6e910b7216e6720d19633b37c3150438e5757bf253c1ab165fdb224a4a2e2946261ef75dd42d437a6422960608d2c8a3d91bbcea569640cc09",
          "sha256": "76198dcb99f3e273e241f64167c666e1cc7b22526162499b866e4c9b3cb6feb8",
          "sha1": "b398b3df91be5054de8073221527bee9d9107650",
          "md5": "007f3f3070faf26fd3f4bf23d377a63b"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "quarkdown-stdlib-2.3.1-sources.jar",
          "url": "quarkdown-stdlib-2.3.1-sources.jar",
          "size": 79631,
          "sha512": "30aeabb4b9e3c6bf482bef30899447879a8a324a3010fb6165b14eabbee52718ce0af8bd794dc9759ec15f39e1fa6262b8a40380192a50c23d37d855ec25290a",
          "sha256": "e775cbc5625c3ad84b9006b0d6666d1365255ce648916bb15683cb34e50aa4da",
          "sha1": "8f3156e693e1d20e708148cb711e71b80fbbb3b5",
          "md5": "af93a14debdb4cd8352c2a74fe7d17aa"
        },
        {
          "name": "quarkdown-stdlib-2.3.1-sources.jar",
          "url": "quarkdown-stdlib-2.3.1-sources.jar",
          "size": 79631,
          "sha512": "30aeabb4b9e3c6bf482bef30899447879a8a324a3010fb6165b14eabbee52718ce0af8bd794dc9759ec15f39e1fa6262b8a40380192a50c23d37d855ec25290a",
          "sha256": "e775cbc5625c3ad84b9006b0d6666d1365255ce648916bb15683cb34e50aa4da",
          "sha1": "8f3156e693e1d20e708148cb711e71b80fbbb3b5",
          "md5": "af93a14debdb4cd8352c2a74fe7d17aa"
        }
      ]
    }
  ]
}
