{
  "formatVersion": "1.1",
  "component": {
    "group": "com.quarkdown",
    "module": "quarkdown-html",
    "version": "2.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        }
      ],
      "files": [
        {
          "name": "quarkdown-html-2.2.0.jar",
          "url": "quarkdown-html-2.2.0.jar",
          "size": 833578,
          "sha512": "c82da46eda1418ac75ac9092138eb46da080bc8dd6a4bb6521de8500a53d41dbc26f7323ddba5ea1331dc39946114e2d5ae034edb9cdf31bd04d35641596bf57",
          "sha256": "d6b19bdbf04208648dece25b27953103029bf259eaa176b662ba48619366d50f",
          "sha1": "6350eb13852644f2bbf37c0d517e8bc4812f7563",
          "md5": "8daf16d3ed17121a42e414c70c95a396"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.quarkdown",
          "module": "quarkdown-core",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "com.quarkdown",
          "module": "quarkdown-interaction",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "com.quarkdown",
          "module": "quarkdown-server",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "com.quarkdown",
          "module": "quarkdown-plaintext",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "com.quarkdown",
          "module": "quarkdown-install-layout-navigator",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-html-jvm",
          "version": {
            "requires": "0.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        }
      ],
      "files": [
        {
          "name": "quarkdown-html-2.2.0.jar",
          "url": "quarkdown-html-2.2.0.jar",
          "size": 833578,
          "sha512": "c82da46eda1418ac75ac9092138eb46da080bc8dd6a4bb6521de8500a53d41dbc26f7323ddba5ea1331dc39946114e2d5ae034edb9cdf31bd04d35641596bf57",
          "sha256": "d6b19bdbf04208648dece25b27953103029bf259eaa176b662ba48619366d50f",
          "sha1": "6350eb13852644f2bbf37c0d517e8bc4812f7563",
          "md5": "8daf16d3ed17121a42e414c70c95a396"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "quarkdown-html-2.2.0-sources.jar",
          "url": "quarkdown-html-2.2.0-sources.jar",
          "size": 673519,
          "sha512": "9dfc74050ad9be357b528ea3aa9a33df8dafbb5fb02d30e5286ca7ed955835eb0e75c3fb87d32eeb0a70d1a14714f3088a0aabd6a4914ec0ad6b5e31ef545c14",
          "sha256": "5244feb33ad1be76e3b3bb751521ed5f8eaae5616d42f83fb3b0158559b0a05f",
          "sha1": "4cb469a8a847a7aabe45254b4197e859988f6534",
          "md5": "2ffca35f209480420d00f61b23de8a8c"
        },
        {
          "name": "quarkdown-html-2.2.0-sources.jar",
          "url": "quarkdown-html-2.2.0-sources.jar",
          "size": 673519,
          "sha512": "9dfc74050ad9be357b528ea3aa9a33df8dafbb5fb02d30e5286ca7ed955835eb0e75c3fb87d32eeb0a70d1a14714f3088a0aabd6a4914ec0ad6b5e31ef545c14",
          "sha256": "5244feb33ad1be76e3b3bb751521ed5f8eaae5616d42f83fb3b0158559b0a05f",
          "sha1": "4cb469a8a847a7aabe45254b4197e859988f6534",
          "md5": "2ffca35f209480420d00f61b23de8a8c"
        }
      ]
    }
  ]
}
