{
  "formatVersion": "1.1",
  "component": {
    "group": "com.quarkdown",
    "module": "quarkdown-html",
    "version": "2.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.10"
          }
        }
      ],
      "files": [
        {
          "name": "quarkdown-html-2.1.2.jar",
          "url": "quarkdown-html-2.1.2.jar",
          "size": 833779,
          "sha512": "330ea35e6c9281f4238522f3b23e8248ba2f7be5aff1a46d1043a5e3a0e4e8734d3d203aacbc66e022dd7ff994bf5ff1a9edabd594fcb6502d0d8be494069634",
          "sha256": "0f4ed4cfb35fdf7aa5b4662c6eaa8fff80d3d19e6517b982a0240af0bffc0030",
          "sha1": "2727619daefacbce43fc9704032fdea15fc6111f",
          "md5": "02225e404b86e8211951928c4174d872"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.quarkdown",
          "module": "quarkdown-core",
          "version": {
            "requires": "2.1.2"
          }
        },
        {
          "group": "com.quarkdown",
          "module": "quarkdown-interaction",
          "version": {
            "requires": "2.1.2"
          }
        },
        {
          "group": "com.quarkdown",
          "module": "quarkdown-server",
          "version": {
            "requires": "2.1.2"
          }
        },
        {
          "group": "com.quarkdown",
          "module": "quarkdown-plaintext",
          "version": {
            "requires": "2.1.2"
          }
        },
        {
          "group": "com.quarkdown",
          "module": "quarkdown-install-layout-navigator",
          "version": {
            "requires": "2.1.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-html-jvm",
          "version": {
            "requires": "0.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.10"
          }
        }
      ],
      "files": [
        {
          "name": "quarkdown-html-2.1.2.jar",
          "url": "quarkdown-html-2.1.2.jar",
          "size": 833779,
          "sha512": "330ea35e6c9281f4238522f3b23e8248ba2f7be5aff1a46d1043a5e3a0e4e8734d3d203aacbc66e022dd7ff994bf5ff1a9edabd594fcb6502d0d8be494069634",
          "sha256": "0f4ed4cfb35fdf7aa5b4662c6eaa8fff80d3d19e6517b982a0240af0bffc0030",
          "sha1": "2727619daefacbce43fc9704032fdea15fc6111f",
          "md5": "02225e404b86e8211951928c4174d872"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "quarkdown-html-2.1.2-sources.jar",
          "url": "quarkdown-html-2.1.2-sources.jar",
          "size": 673637,
          "sha512": "9088443db7b96e44e8ceefedac977dbbbdb9e1a671530bc6c2f2fb8b30cbf0c7c571bfa3c478f18c6a7fed9f4f2fc55219a8f3b8c50132151ac1f4e470f02121",
          "sha256": "1d286a9f97460d4cafe5805ea4d878c14c45d5c890b2704715bd9688cab82f42",
          "sha1": "e7c6f0f733a2fb31e95eac2e73d19cb628a25bc7",
          "md5": "66d074f19e26c8734d91bf7901f1b2ba"
        },
        {
          "name": "quarkdown-html-2.1.2-sources.jar",
          "url": "quarkdown-html-2.1.2-sources.jar",
          "size": 673637,
          "sha512": "9088443db7b96e44e8ceefedac977dbbbdb9e1a671530bc6c2f2fb8b30cbf0c7c571bfa3c478f18c6a7fed9f4f2fc55219a8f3b8c50132151ac1f4e470f02121",
          "sha256": "1d286a9f97460d4cafe5805ea4d878c14c45d5c890b2704715bd9688cab82f42",
          "sha1": "e7c6f0f733a2fb31e95eac2e73d19cb628a25bc7",
          "md5": "66d074f19e26c8734d91bf7901f1b2ba"
        }
      ]
    }
  ]
}
