{
  "formatVersion": "1.1",
  "component": {
    "group": "com.quarkdown",
    "module": "quarkdown-stdlib",
    "version": "2.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.10"
          }
        }
      ],
      "files": [
        {
          "name": "quarkdown-stdlib-2.0.1.jar",
          "url": "quarkdown-stdlib-2.0.1.jar",
          "size": 306655,
          "sha512": "85b1eef7eba3ab5448471340f229b3aa56ecaa75740b50cf0e135eb46e841fd07f1ea38bfd67578d96e2c922b18e86d40f9a9536bc473c77730cd2cb8f5688b5",
          "sha256": "0b6e2634618bfcb8a202c731fe46cb52f227876d044b6d2e8284baa7e91bc2b6",
          "sha1": "9349b128342f455787d3265b344161b4b6fe8291",
          "md5": "91d3c51b3400bae7e6b3d322876785bb"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.quarkdown",
          "module": "quarkdown-core",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "se.sawano.java",
          "module": "alphanumeric-comparator",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "com.github.doyaaaaaken",
          "module": "kotlin-csv-jvm",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.kodein.emoji",
          "module": "emoji-kt",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.10"
          }
        }
      ],
      "files": [
        {
          "name": "quarkdown-stdlib-2.0.1.jar",
          "url": "quarkdown-stdlib-2.0.1.jar",
          "size": 306655,
          "sha512": "85b1eef7eba3ab5448471340f229b3aa56ecaa75740b50cf0e135eb46e841fd07f1ea38bfd67578d96e2c922b18e86d40f9a9536bc473c77730cd2cb8f5688b5",
          "sha256": "0b6e2634618bfcb8a202c731fe46cb52f227876d044b6d2e8284baa7e91bc2b6",
          "sha1": "9349b128342f455787d3265b344161b4b6fe8291",
          "md5": "91d3c51b3400bae7e6b3d322876785bb"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "quarkdown-stdlib-2.0.1-sources.jar",
          "url": "quarkdown-stdlib-2.0.1-sources.jar",
          "size": 75791,
          "sha512": "d45dc69f8c94f0ffa2f9052f7713be7d13b53fe0247afdcdd7a3f113ae5645dd1856f093b3ea18ccc46632b9395668e9a6b160de0d1f93f1e3729f122f0bffbb",
          "sha256": "305f1348bdbcce0de1b3e7b8a4f2926dd98e391bb9b859ff01379b5b85082f8b",
          "sha1": "0488e906da7c083322cd55b12e8bddce2b127c76",
          "md5": "55bc788c320e6e1e1df74e9f723de15c"
        },
        {
          "name": "quarkdown-stdlib-2.0.1-sources.jar",
          "url": "quarkdown-stdlib-2.0.1-sources.jar",
          "size": 75791,
          "sha512": "d45dc69f8c94f0ffa2f9052f7713be7d13b53fe0247afdcdd7a3f113ae5645dd1856f093b3ea18ccc46632b9395668e9a6b160de0d1f93f1e3729f122f0bffbb",
          "sha256": "305f1348bdbcce0de1b3e7b8a4f2926dd98e391bb9b859ff01379b5b85082f8b",
          "sha1": "0488e906da7c083322cd55b12e8bddce2b127c76",
          "md5": "55bc788c320e6e1e1df74e9f723de15c"
        }
      ]
    }
  ]
}
