{
  "formatVersion": "1.1",
  "component": {
    "group": "com.quarkdown",
    "module": "quarkdown-lsp",
    "version": "2.3.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        }
      ],
      "files": [
        {
          "name": "quarkdown-lsp-2.3.1.jar",
          "url": "quarkdown-lsp-2.3.1.jar",
          "size": 160507,
          "sha512": "89cac68ed680d4929e6d88a69d36059266859f8bb120b2b231f2e043bf40a97e4f69c97f02288346d51ffa22c9cd476109bf5115a43bc59ddac789b5183b6256",
          "sha256": "f1b51aa1efd9f54d4878b822bc51896b472dcc5d6da033a3658787d0411cd02d",
          "sha1": "0ad9afec994c42586a62ea0499fc44d25c488619",
          "md5": "872dc002daad7464f4cb12ff9edd70ac"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.eclipse.lsp4j",
          "module": "org.eclipse.lsp4j",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.github.h0tk3y.betterParse",
          "module": "better-parse",
          "version": {
            "requires": "0.4.4"
          }
        },
        {
          "group": "com.vladsch.flexmark",
          "module": "flexmark-html2md-converter",
          "version": {
            "requires": "0.64.8"
          }
        },
        {
          "group": "com.quarkdown",
          "module": "quarkdown-core",
          "version": {
            "requires": "2.3.1"
          }
        },
        {
          "group": "com.quarkdown",
          "module": "quarkdown-quarkdoc-reader",
          "version": {
            "requires": "2.3.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        }
      ],
      "files": [
        {
          "name": "quarkdown-lsp-2.3.1.jar",
          "url": "quarkdown-lsp-2.3.1.jar",
          "size": 160507,
          "sha512": "89cac68ed680d4929e6d88a69d36059266859f8bb120b2b231f2e043bf40a97e4f69c97f02288346d51ffa22c9cd476109bf5115a43bc59ddac789b5183b6256",
          "sha256": "f1b51aa1efd9f54d4878b822bc51896b472dcc5d6da033a3658787d0411cd02d",
          "sha1": "0ad9afec994c42586a62ea0499fc44d25c488619",
          "md5": "872dc002daad7464f4cb12ff9edd70ac"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "quarkdown-lsp-2.3.1-sources.jar",
          "url": "quarkdown-lsp-2.3.1-sources.jar",
          "size": 63870,
          "sha512": "bc03409858ed5b56f0909492054b7c52aa311c03754a8743a85394c6dadc7cc73ac12d9aad168b2702f7073665fd56c00855841f88666fc05ed49a5548418374",
          "sha256": "04d1c0fce6f075964d61b2722e1ffa09afbdb423f27ce57879ab662fcb670096",
          "sha1": "4530037b78001a55876fd3f14c344ce64286ce2c",
          "md5": "58ab8cac845b906487d05e0cccbbeb31"
        },
        {
          "name": "quarkdown-lsp-2.3.1-sources.jar",
          "url": "quarkdown-lsp-2.3.1-sources.jar",
          "size": 63870,
          "sha512": "bc03409858ed5b56f0909492054b7c52aa311c03754a8743a85394c6dadc7cc73ac12d9aad168b2702f7073665fd56c00855841f88666fc05ed49a5548418374",
          "sha256": "04d1c0fce6f075964d61b2722e1ffa09afbdb423f27ce57879ab662fcb670096",
          "sha1": "4530037b78001a55876fd3f14c344ce64286ce2c",
          "md5": "58ab8cac845b906487d05e0cccbbeb31"
        }
      ]
    }
  ]
}
