{
  "formatVersion": "1.1",
  "component": {
    "group": "com.quarkdown",
    "module": "quarkdown-quarkdoc",
    "version": "2.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.10"
          }
        }
      ],
      "files": [
        {
          "name": "quarkdown-quarkdoc-2.0.1.jar",
          "url": "quarkdown-quarkdoc-2.0.1.jar",
          "size": 213699,
          "sha512": "5bca2bc358cbf41e8e2efbb3660567b75fbbc53bcd8158f64979d9ba516143abbff821907837fae1b3db024c7be1f556de697942e8d6ef29d89867818fe070fd",
          "sha256": "4acb2dbd00f4ec83de8ce23c86d3d28fdbf40663cdef49bc71ed64bfc77a4188",
          "sha1": "17f94a0991a16eda1ad629513e6a8dbd254593e5",
          "md5": "2c38703f4ddda300b1c089bed3840442"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.quarkdown",
          "module": "quarkdown-core",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "com.quarkdown",
          "module": "quarkdown-quarkdoc-reader",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect"
        },
        {
          "group": "org.jetbrains.dokka",
          "module": "dokka-base",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.10"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "2.3.10"
          }
        }
      ],
      "files": [
        {
          "name": "quarkdown-quarkdoc-2.0.1.jar",
          "url": "quarkdown-quarkdoc-2.0.1.jar",
          "size": 213699,
          "sha512": "5bca2bc358cbf41e8e2efbb3660567b75fbbc53bcd8158f64979d9ba516143abbff821907837fae1b3db024c7be1f556de697942e8d6ef29d89867818fe070fd",
          "sha256": "4acb2dbd00f4ec83de8ce23c86d3d28fdbf40663cdef49bc71ed64bfc77a4188",
          "sha1": "17f94a0991a16eda1ad629513e6a8dbd254593e5",
          "md5": "2c38703f4ddda300b1c089bed3840442"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "quarkdown-quarkdoc-2.0.1-sources.jar",
          "url": "quarkdown-quarkdoc-2.0.1-sources.jar",
          "size": 56236,
          "sha512": "beadec67ea9bae4fdd0eb434a0f617621b02dc3527f3889688bf17d7f043421034c841631265a277fc2edcbf570255bbb006113e2834dfabf40ef0f62216b54f",
          "sha256": "1a5f7f77262c4f76c5234a4c16190b4f93ae8275cdba5a6e0622af07f0e081dd",
          "sha1": "b87f43589ae55285b77283dc95c701d8f969d854",
          "md5": "0281b9dbb03d7bb2ef19d7f47cbb3c64"
        },
        {
          "name": "quarkdown-quarkdoc-2.0.1-sources.jar",
          "url": "quarkdown-quarkdoc-2.0.1-sources.jar",
          "size": 56236,
          "sha512": "beadec67ea9bae4fdd0eb434a0f617621b02dc3527f3889688bf17d7f043421034c841631265a277fc2edcbf570255bbb006113e2834dfabf40ef0f62216b54f",
          "sha256": "1a5f7f77262c4f76c5234a4c16190b4f93ae8275cdba5a6e0622af07f0e081dd",
          "sha1": "b87f43589ae55285b77283dc95c701d8f969d854",
          "md5": "0281b9dbb03d7bb2ef19d7f47cbb3c64"
        }
      ]
    }
  ]
}
