{
  "formatVersion": "1.1",
  "component": {
    "group": "com.quarkdown",
    "module": "quarkdown-plaintext",
    "version": "2.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        }
      ],
      "files": [
        {
          "name": "quarkdown-plaintext-2.2.0.jar",
          "url": "quarkdown-plaintext-2.2.0.jar",
          "size": 27929,
          "sha512": "39632e39142293d8e82f125b5f2db7be55609b1143a1fedcb4c9cff298112c0bd6b424e3b0e5b776b338964e370688deea6154029f69f6631543a83c6b9604a2",
          "sha256": "e521463a463c5bbcedde15aca9993b7d61983917c4e87512d7b1b83c81638e51",
          "sha1": "b936930f261eb1088ba131c6be091107c32b0d26",
          "md5": "647ffab4cefb73987d7b2a53433d8f6a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.quarkdown",
          "module": "quarkdown-core",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        }
      ],
      "files": [
        {
          "name": "quarkdown-plaintext-2.2.0.jar",
          "url": "quarkdown-plaintext-2.2.0.jar",
          "size": 27929,
          "sha512": "39632e39142293d8e82f125b5f2db7be55609b1143a1fedcb4c9cff298112c0bd6b424e3b0e5b776b338964e370688deea6154029f69f6631543a83c6b9604a2",
          "sha256": "e521463a463c5bbcedde15aca9993b7d61983917c4e87512d7b1b83c81638e51",
          "sha1": "b936930f261eb1088ba131c6be091107c32b0d26",
          "md5": "647ffab4cefb73987d7b2a53433d8f6a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "quarkdown-plaintext-2.2.0-sources.jar",
          "url": "quarkdown-plaintext-2.2.0-sources.jar",
          "size": 17633,
          "sha512": "a7adca73e8c1f45009d9ff1738aecb6a457fa9292cdd8d669a5853306c2795cad20873d2de4d0722d9a8670fb4080ef5e9178bb9b21d84d9844c7106d7e8480a",
          "sha256": "9fe1a318b2e5c6eb95e968ffcb1d6c8db0d786a5a51be242b2ecb0143deafed4",
          "sha1": "e16face29c1419392f713d195dd2537521e33e24",
          "md5": "2b50483195ce3fae2c006bca238fbc09"
        },
        {
          "name": "quarkdown-plaintext-2.2.0-sources.jar",
          "url": "quarkdown-plaintext-2.2.0-sources.jar",
          "size": 17633,
          "sha512": "a7adca73e8c1f45009d9ff1738aecb6a457fa9292cdd8d669a5853306c2795cad20873d2de4d0722d9a8670fb4080ef5e9178bb9b21d84d9844c7106d7e8480a",
          "sha256": "9fe1a318b2e5c6eb95e968ffcb1d6c8db0d786a5a51be242b2ecb0143deafed4",
          "sha1": "e16face29c1419392f713d195dd2537521e33e24",
          "md5": "2b50483195ce3fae2c006bca238fbc09"
        }
      ]
    }
  ]
}
