{
  "formatVersion": "1.1",
  "component": {
    "group": "com.quarkdown",
    "module": "quarkdown-lsp",
    "version": "2.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.10"
          }
        }
      ],
      "files": [
        {
          "name": "quarkdown-lsp-2.0.1.jar",
          "url": "quarkdown-lsp-2.0.1.jar",
          "size": 159044,
          "sha512": "6331af43fbec5d1c18b7926c3d67059c76710cf5b1b60e531a75cd3641ba091a4d3c02603ca28fe2860299bded82d12c5628815e1141d04bed8a742016eb5ad1",
          "sha256": "078c2fa97f11292b1f40162bd9d12abf15492e7829d299a6e35565f1bdc50b83",
          "sha1": "83376fe38dd22ad754d0caf83c46c37c9596e745",
          "md5": "e775b67ab4e4de1043b69e9b5ec9ebeb"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.eclipse.lsp4j",
          "module": "org.eclipse.lsp4j",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.github.h0tk3y.betterParse",
          "module": "better-parse",
          "version": {
            "requires": "0.4.4"
          }
        },
        {
          "group": "com.vladsch.flexmark",
          "module": "flexmark-html2md-converter",
          "version": {
            "requires": "0.64.8"
          }
        },
        {
          "group": "com.quarkdown",
          "module": "quarkdown-core",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "com.quarkdown",
          "module": "quarkdown-quarkdoc-reader",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.10"
          }
        }
      ],
      "files": [
        {
          "name": "quarkdown-lsp-2.0.1.jar",
          "url": "quarkdown-lsp-2.0.1.jar",
          "size": 159044,
          "sha512": "6331af43fbec5d1c18b7926c3d67059c76710cf5b1b60e531a75cd3641ba091a4d3c02603ca28fe2860299bded82d12c5628815e1141d04bed8a742016eb5ad1",
          "sha256": "078c2fa97f11292b1f40162bd9d12abf15492e7829d299a6e35565f1bdc50b83",
          "sha1": "83376fe38dd22ad754d0caf83c46c37c9596e745",
          "md5": "e775b67ab4e4de1043b69e9b5ec9ebeb"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "quarkdown-lsp-2.0.1-sources.jar",
          "url": "quarkdown-lsp-2.0.1-sources.jar",
          "size": 62722,
          "sha512": "fd64eb1092219fe4e1ffd38adba7fd3bfb7c2f81986dfa2f4755a2bc14f7cd83a3b24b7bbb2f50be2d22a38b60b100e7bead9796371db8d7483016425c829450",
          "sha256": "5e263a5d3cef667bcfaa2384f8453e54f1103fe39f904d7291e70f6216f42239",
          "sha1": "a9ab243f7a3359a537e03bca94543923028394ac",
          "md5": "a0c7b9ecec9478cf7c7e073fd333f639"
        },
        {
          "name": "quarkdown-lsp-2.0.1-sources.jar",
          "url": "quarkdown-lsp-2.0.1-sources.jar",
          "size": 62722,
          "sha512": "fd64eb1092219fe4e1ffd38adba7fd3bfb7c2f81986dfa2f4755a2bc14f7cd83a3b24b7bbb2f50be2d22a38b60b100e7bead9796371db8d7483016425c829450",
          "sha256": "5e263a5d3cef667bcfaa2384f8453e54f1103fe39f904d7291e70f6216f42239",
          "sha1": "a9ab243f7a3359a537e03bca94543923028394ac",
          "md5": "a0c7b9ecec9478cf7c7e073fd333f639"
        }
      ]
    }
  ]
}
